// Map Yoto icon tags/titles to emoji representations
// This provides visual feedback in the UI since we can't display actual Yoto icons

const TAG_TO_EMOJI: Record<string, string> = {
  // Animals
  fish: '🐟',
  shark: '🦈',
  dog: '🐕',
  cat: '🐱',
  bird: '🐦',
  elephant: '🐘',
  lion: '🦁',
  tiger: '🐯',
  monkey: '🐒',
  bear: '🐻',
  bunny: '🐰',
  rabbit: '🐰',
  duck: '🦆',
  cow: '🐄',
  pig: '🐷',
  horse: '🐴',
  sheep: '🐑',
  frog: '🐸',
  butterfly: '🦋',
  bee: '🐝',
  spider: '🕷️',
  dinosaur: '🦕',
  dragon: '🐉',
  unicorn: '🦄',
  animals: '🐾',
  pets: '🐾',
  safari: '🦁',
  farm: '🚜',
  birds: '🐦',
  insects: '🐛',
  dinosaurs: '🦖',
  sea: '🌊',
  ocean: '🌊',

  // Nature & Weather
  moon: '🌙',
  night: '🌙',
  stars: '⭐',
  star: '⭐',
  sun: '☀️',
  rainbow: '🌈',
  weather: '🌤️',
  rain: '🌧️',
  clouds: '☁️',
  snow: '❄️',
  flower: '🌸',
  flowers: '🌸',
  tree: '🌳',
  trees: '🌲',
  nature: '🌿',
  forest: '🌲',
  beach: '🏖️',
  mountain: '⛰️',
  mountains: '🏔️',

  // Music & Entertainment
  music: '🎵',
  microphone: '🎤',
  instruments: '🎸',
  piano: '🎹',
  guitar: '🎸',
  drum: '🥁',
  drums: '🥁',

  // Vehicles
  vehicles: '🚗',
  transport: '🚌',
  bus: '🚌',
  car: '🚗',
  train: '🚂',
  plane: '✈️',
  boat: '⛵',
  sailboat: '⛵',
  ship: '🚢',
  rocket: '🚀',
  truck: '🚚',
  tractor: '🚜',
  space: '🚀',
  bicycle: '🚲',
  motorcycle: '🏍️',
  helicopter: '🚁',
  water: '💧',

  // Holidays & Celebrations
  christmas: '🎄',
  holiday: '🎉',
  halloween: '🎃',
  spooky: '👻',
  birthday: '🎂',
  party: '🎉',
  celebration: '🎊',
  easter: '🐣',
  spring: '🌷',
  autumn: '🍂',
  love: '❤️',
  hearts: '💕',

  // People & Characters
  baby: '👶',
  family: '👨‍👩‍👧',
  friends: '👫',
  princess: '👸',
  prince: '🤴',
  royalty: '👑',
  king: '👑',
  queen: '👑',
  pirate: '🏴‍☠️',
  pirates: '🏴‍☠️',
  superhero: '🦸',
  heroes: '🦸',
  adventure: '🗺️',
  fairy: '🧚',
  fantasy: '✨',
  magic: '✨',

  // Food
  food: '🍎',
  fruits: '🍎',
  dessert: '🍰',
  cake: '🎂',
  pizza: '🍕',

  // Learning
  learning: '📚',
  alphabet: '🔤',
  numbers: '🔢',
  colors: '🎨',
  shapes: '🔷',
  school: '🏫',

  // Activities
  games: '🎮',
  toys: '🧸',
  sports: '⚽',
  swimming: '🏊',
  sleep: '😴',

  // Misc
  default: '🎵',
};

// Keywords in icon titles that map to emojis
const TITLE_KEYWORDS: Record<string, string> = {
  shark: '🦈',
  fish: '🐟',
  whale: '🐋',
  dolphin: '🐬',
  octopus: '🐙',
  crab: '🦀',
  turtle: '🐢',
  dog: '🐕',
  puppy: '🐶',
  cat: '🐱',
  kitten: '🐱',
  bird: '🐦',
  owl: '🦉',
  penguin: '🐧',
  duck: '🦆',
  chicken: '🐔',
  lion: '🦁',
  tiger: '🐯',
  bear: '🐻',
  panda: '🐼',
  koala: '🐨',
  monkey: '🐒',
  elephant: '🐘',
  giraffe: '🦒',
  zebra: '🦓',
  horse: '🐴',
  unicorn: '🦄',
  cow: '🐄',
  pig: '🐷',
  sheep: '🐑',
  goat: '🐐',
  rabbit: '🐰',
  bunny: '🐰',
  mouse: '🐭',
  hamster: '🐹',
  frog: '🐸',
  snake: '🐍',
  dragon: '🐉',
  dinosaur: '🦕',
  butterfly: '🦋',
  bee: '🐝',
  ladybug: '🐞',
  spider: '🕷️',
  snail: '🐌',
  moon: '🌙',
  star: '⭐',
  sun: '☀️',
  cloud: '☁️',
  rainbow: '🌈',
  rain: '🌧️',
  snow: '❄️',
  flower: '🌸',
  tree: '🌳',
  leaf: '🍃',
  mushroom: '🍄',
  heart: '❤️',
  love: '💕',
  music: '🎵',
  note: '🎵',
  guitar: '🎸',
  piano: '🎹',
  drum: '🥁',
  microphone: '🎤',
  car: '🚗',
  bus: '🚌',
  train: '🚂',
  plane: '✈️',
  rocket: '🚀',
  boat: '⛵',
  ship: '🚢',
  bicycle: '🚲',
  tractor: '🚜',
  truck: '🚚',
  christmas: '🎄',
  santa: '🎅',
  snowman: '⛄',
  gift: '🎁',
  present: '🎁',
  halloween: '🎃',
  pumpkin: '🎃',
  ghost: '👻',
  witch: '🧙',
  birthday: '🎂',
  cake: '🎂',
  balloon: '🎈',
  party: '🎉',
  crown: '👑',
  princess: '👸',
  prince: '🤴',
  castle: '🏰',
  fairy: '🧚',
  wizard: '🧙',
  pirate: '🏴‍☠️',
  robot: '🤖',
  alien: '👽',
  superhero: '🦸',
  baby: '👶',
  boy: '👦',
  girl: '👧',
  family: '👨‍👩‍👧',
  book: '📚',
  pencil: '✏️',
  paint: '🎨',
  ball: '⚽',
  teddy: '🧸',
  toy: '🧸',
  block: '🧱',
  pizza: '🍕',
  apple: '🍎',
  banana: '🍌',
  cookie: '🍪',
  candy: '🍬',
  ice: '🍦',
  cream: '🍦',
};

/**
 * Get an emoji representation for a Yoto icon
 */
export function getIconEmoji(icon: { title?: string; publicTags?: string[] }): string {
  // First try to match by title keywords
  if (icon.title) {
    const titleLower = icon.title.toLowerCase();
    for (const [keyword, emoji] of Object.entries(TITLE_KEYWORDS)) {
      if (titleLower.includes(keyword)) {
        return emoji;
      }
    }
  }

  // Then try to match by tags
  if (icon.publicTags && icon.publicTags.length > 0) {
    for (const tag of icon.publicTags) {
      const tagLower = tag.toLowerCase();
      if (TAG_TO_EMOJI[tagLower]) {
        return TAG_TO_EMOJI[tagLower];
      }
    }
  }

  // Default music emoji
  return TAG_TO_EMOJI.default;
}
